import { Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Menu, X, MessageCircle } from "lucide-react";
import { settingsQuery } from "@/lib/queries";
import { mediaUrl } from "@/lib/media";
import { whatsappLink } from "@/lib/whatsapp";
import { Button } from "@/components/ui/button";
const NAV=[{to:"/",label:"Home"},{to:"/about",label:"About"},{to:"/products",label:"Products"},{to:"/services",label:"Services"},{to:"/gallery",label:"Gallery"},{to:"/contact",label:"Contact"}] as const;
export function Header(){const{data:settings}=useQuery(settingsQuery);const[open,setOpen]=useState(false);const logo=mediaUrl(settings?.logo_url);const wa=whatsappLink(settings?.whatsapp_number,"Hello, I would like to know more.");return <header className="sticky top-0 z-50 border-b border-border/70 bg-background/85 backdrop-blur-md"><div className="section-shell flex h-16 items-center justify-between gap-4 md:h-20"><Link to="/" className="flex min-w-0 items-center gap-3" onClick={()=>setOpen(false)}>{logo?<img src={logo} alt="" className="h-10 w-10 rounded-full object-cover"/>:<span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary font-display text-sm font-semibold text-primary-foreground">{(settings?.business_name??"Aaron Sau").slice(0,2).toUpperCase()}</span>}<span className="truncate font-display text-lg font-semibold tracking-tight md:text-xl">{settings?.business_name??"Aaron Sau"}</span></Link><nav className="hidden items-center gap-1 lg:flex">{NAV.map(item=><Link key={item.to} to={item.to} activeOptions={{exact:item.to==="/" }} activeProps={{className:"bg-accent text-accent-foreground"}} className="rounded-md px-3 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-accent/60 hover:text-foreground">{item.label}</Link>)}</nav><div className="flex items-center gap-2">{wa?<a href={wa} target="_blank" rel="noopener noreferrer" className="hidden sm:inline-flex"><Button size="sm" variant="whatsapp"><MessageCircle className="size-4"/> WhatsApp</Button></a>:<Link to="/contact" className="hidden sm:inline-flex"><Button size="sm">Contact</Button></Link>}<button type="button" aria-label={open?"Close menu":"Open menu"} aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="inline-flex size-10 items-center justify-center rounded-md border border-border text-foreground lg:hidden">{open?<X className="size-5"/>:<Menu className="size-5"/>}</button></div></div>{open?<div className="border-t border-border bg-background lg:hidden"><nav className="section-shell flex flex-col py-3">{NAV.map(item=><Link key={item.to} to={item.to} activeOptions={{exact:item.to==="/" }} activeProps={{className:"text-primary"}} onClick={()=>setOpen(false)} className="rounded-md px-2 py-3 text-base font-medium text-foreground/90">{item.label}</Link>)}{wa?<a href={wa} target="_blank" rel="noopener noreferrer" className="mt-2"><Button variant="whatsapp" className="w-full"><MessageCircle className="size-4"/> WhatsApp us</Button></a>:null}</nav></div>:null}</header>}